# Generated by Django 5.2.5 on 2025-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='formatted_text',
            field=models.BooleanField(default=False, verbose_name='Sformatowany tekst'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='text_processed',
            field=models.TextField(blank=True, null=True, verbose_name='Przygotowany tekst'),
        ),
    ]
